// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HerbSys.HerbSys_Specflow
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("CadastraCliente", SourceFile="HerbSys.Specflow\\SpecFlowFeature1.feature", SourceLine=0)]
    public partial class CadastraClienteFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SpecFlowFeature1.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CadastraCliente", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void CadastroComDadosValidos(string cpf_Cnpj, string nome, string endereco, string cep, string bairro, string cidade, string uf, string telefone, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "CadastraCliente"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro com dados validos", @__tags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("Eu estou na tela de cadastro de cliente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.And(string.Format("eu informei {0}", cpf_Cnpj), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And(string.Format("eu informei {0}", nome), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And(string.Format("eu informei {0}", endereco), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And(string.Format("eu informei {0}", cep), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And(string.Format("eu informei {0}", bairro), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And(string.Format("eu informei {0}", cidade), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And(string.Format("eu informei {0}", uf), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And(string.Format("eu informei {0}", telefone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.When("Eu finalizei o cadastro do cliente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.Then("o cadastro deve ser realizado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastro com dados validos, \'0990263018\'", new string[] {
                "CadastraCliente"}, SourceLine=18)]
        public virtual void CadastroComDadosValidos_0990263018()
        {
#line 4
this.CadastroComDadosValidos("\'0990263018\'", "\'Augusto Santos Coelho\'", "\'Rua Dr Dido Fontes\'", "\'29060280\'", "\'Jardim da Penha\'", "\'Vitoria\'", "\'ES\'", "\'(27)997015055\'", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastro com dados validos, \'31850435000159\'", new string[] {
                "CadastraCliente"}, SourceLine=18)]
        public virtual void CadastroComDadosValidos_31850435000159()
        {
#line 4
this.CadastroComDadosValidos("\'31850435000159\'", "\'Churrasquinho de Gato\'", "\'Avenidas das Prima\'", "\'29060010\'", "\'Centro\'", "\'Caraiva\'", "\'BA\'", "\'(73)33606669\'", ((string[])(null)));
#line hidden
        }
        
        public virtual void CadastroComDadosInvalidos(string cpf_Cnpj, string nome, string endereco, string cep, string bairro, string cidade, string uf, string telefone, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro com dados invalidos", exampleTags);
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.Given("Eu estou na tela de cadastro de cliente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
 testRunner.And(string.Format("eu informei {0}", cpf_Cnpj), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And(string.Format("eu informei {0}", nome), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And(string.Format("eu informei {0}", endereco), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And(string.Format("eu informei {0}", cep), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And(string.Format("eu informei {0}", bairro), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And(string.Format("eu informei {0}", cidade), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And(string.Format("eu informei {0}", uf), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And(string.Format("eu informei {0}", telefone), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.When("Eu finalizei o cadastro do cliente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
 testRunner.Then("o cadastro deve ser bloquado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastro com dados invalidos, ", SourceLine=36)]
        public virtual void CadastroComDadosInvalidos_()
        {
#line 22
this.CadastroComDadosInvalidos("", "\'Augusto Santos Coelho\'", "\'Rua Dr Dido Fontes\'", "\'29060280\'", "\'Jardim da Penha\'", "\'Vitoria\'", "\'ES\'", "\'(27)997015055\'", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastro com dados invalidos, \'1\'", SourceLine=36)]
        public virtual void CadastroComDadosInvalidos_1()
        {
#line 22
this.CadastroComDadosInvalidos("\'1\'", "\'Churrasquinho de Gato\'", "\'Avenidas das Prima\'", "\'29060010\'", "\'Centro\'", "\'Caraiva\'", "\'BA\'", "\'(73)33606669\'", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastro com dados invalidos, \'12\'", SourceLine=36)]
        public virtual void CadastroComDadosInvalidos_12()
        {
#line 22
this.CadastroComDadosInvalidos("\'12\'", "\'Churrasquinho de Gato\'", "\'Avenidas das Prima\'", "\'29060010\'", "\'Centro\'", "\'Caraiva\'", "\'BA\'", "\'(73)33606669\'", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastro com dados invalidos, \'123\'", SourceLine=36)]
        public virtual void CadastroComDadosInvalidos_123()
        {
#line 22
this.CadastroComDadosInvalidos("\'123\'", "\'Churrasquinho de Gato\'", "\'Avenidas das Prima\'", "\'29060010\'", "\'Centro\'", "\'Caraiva\'", "\'BA\'", "\'(73)33606669\'", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastro com dados invalidos, \'1234\'", SourceLine=36)]
        public virtual void CadastroComDadosInvalidos_1234()
        {
#line 22
this.CadastroComDadosInvalidos("\'1234\'", "\'Churrasquinho de Gato\'", "\'Avenidas das Prima\'", "\'29060010\'", "\'Centro\'", "\'Caraiva\'", "\'BA\'", "\'(73)33606669\'", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastro com dados invalidos, \'12345\'", SourceLine=36)]
        public virtual void CadastroComDadosInvalidos_12345()
        {
#line 22
this.CadastroComDadosInvalidos("\'12345\'", "\'Churrasquinho de Gato\'", "\'Avenidas das Prima\'", "\'29060010\'", "\'Centro\'", "\'Caraiva\'", "\'BA\'", "\'(73)33606669\'", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastro com dados invalidos, \'123456\'", SourceLine=36)]
        public virtual void CadastroComDadosInvalidos_123456()
        {
#line 22
this.CadastroComDadosInvalidos("\'123456\'", "\'Churrasquinho de Gato\'", "\'Avenidas das Prima\'", "\'29060010\'", "\'Centro\'", "\'Caraiva\'", "\'BA\'", "\'(73)33606669\'", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastro com dados invalidos, \'1234567\'", SourceLine=36)]
        public virtual void CadastroComDadosInvalidos_1234567()
        {
#line 22
this.CadastroComDadosInvalidos("\'1234567\'", "\'Churrasquinho de Gato\'", "\'Avenidas das Prima\'", "\'29060010\'", "\'Centro\'", "\'Caraiva\'", "\'BA\'", "\'(73)33606669\'", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastro com dados invalidos, \'12345678\'", SourceLine=36)]
        public virtual void CadastroComDadosInvalidos_12345678()
        {
#line 22
this.CadastroComDadosInvalidos("\'12345678\'", "\'Churrasquinho de Gato\'", "\'Avenidas das Prima\'", "\'29060010\'", "\'Centro\'", "\'Caraiva\'", "\'BA\'", "\'(73)33606669\'", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastro com dados invalidos, \'123456789\'", SourceLine=36)]
        public virtual void CadastroComDadosInvalidos_123456789()
        {
#line 22
this.CadastroComDadosInvalidos("\'123456789\'", "\'Churrasquinho de Gato\'", "\'Avenidas das Prima\'", "\'29060010\'", "\'Centro\'", "\'Caraiva\'", "\'BA\'", "\'(73)33606669\'", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Cadastro com dados invalidos, \'1234567899\'", SourceLine=36)]
        public virtual void CadastroComDadosInvalidos_1234567899()
        {
#line 22
this.CadastroComDadosInvalidos("\'1234567899\'", "\'Churrasquinho de Gato\'", "\'Avenidas das Prima\'", "\'29060010\'", "\'Centro\'", "\'Caraiva\'", "\'BA\'", "\'(73)33606669\'", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
